{{- if .Values.apptest.enabled }}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "glassbox-mol-audit.fullname" . }}-tester
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    marketplace.cloud.google.com/verification: "test"
  labels:
    {{- include "glassbox-mol-audit.labels" . | nindent 4 }}
spec:
  restartPolicy: Never
  serviceAccountName: {{ include "glassbox-mol-audit.serviceAccountName" . | quote }}
  containers:
    - name: tester
      {{- if .Values.apptest.image.digest }}
      image: "{{ .Values.apptest.image.repository }}@{{ .Values.apptest.image.digest }}"
      {{- else }}
      image: "{{ .Values.apptest.image.repository }}:{{ .Values.apptest.image.tag }}"
      {{- end }}
      imagePullPolicy: {{ .Values.apptest.image.pullPolicy }}
      env:
        - name: APP_INSTANCE_NAME
          value: {{ include "glassbox-mol-audit.fullname" . | quote }}
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: APP_CONFIGMAP
          value: {{ printf "%s-config" (include "glassbox-mol-audit.fullname" .) | quote }}
        - name: APP_SERVICE_ACCOUNT
          value: {{ include "glassbox-mol-audit.serviceAccountName" . | quote }}
        - name: APP_PVC_NAME
          value: {{ printf "%s-data" (include "glassbox-mol-audit.fullname" .) | quote }}
        - name: APP_PROJECT_ID
          value: {{ .Values.config.projectId | quote }}
        - name: APP_CATEGORY_ID
          value: {{ .Values.config.categoryId | quote }}
        {{- $runnerRepo := include "glassbox-mol-audit.runnerImageRepository" . }}
        {{- $runnerTag := include "glassbox-mol-audit.runnerImageTag" . }}
        {{- $runnerDigest := include "glassbox-mol-audit.runnerImageDigest" . }}
        {{- if $runnerDigest }}
        - name: APP_RUNTIME_IMAGE
          value: "{{ $runnerRepo }}@{{ $runnerDigest }}"
        {{- else }}
        - name: APP_RUNTIME_IMAGE
          value: "{{ $runnerRepo }}:{{ $runnerTag }}"
        {{- end }}
        {{- if .Values.apptest.image.digest }}
        - name: APP_IO_IMAGE
          value: "{{ .Values.apptest.image.repository }}@{{ .Values.apptest.image.digest }}"
        {{- else }}
        - name: APP_IO_IMAGE
          value: "{{ .Values.apptest.image.repository }}:{{ .Values.apptest.image.tag }}"
        {{- end }}
{{- end }}
