{{- if .Values.ubbagent.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glassbox-mol-audit.fullname" . }}-ubbagent
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "glassbox-mol-audit.labels" . | nindent 4 }}
data:
  config.yaml: |
    identities:
      - name: gcp
        gcp:
          encodedServiceAccountKey: ${MARKETPLACE_REPORTING_KEY_B64}
    metrics:
      - name: {{ .Values.ubbagent.metricNameStandard | quote }}
        type: int
        endpoints:
          - name: servicecontrol
      - name: {{ .Values.ubbagent.metricNameDeep | quote }}
        type: int
        endpoints:
          - name: servicecontrol
      {{- if and .Values.ubbagent.metricName (ne .Values.ubbagent.metricName .Values.ubbagent.metricNameStandard) (ne .Values.ubbagent.metricName .Values.ubbagent.metricNameDeep) }}
      - name: {{ .Values.ubbagent.metricName | quote }}
        type: int
        endpoints:
          - name: servicecontrol
      {{- end }}
    endpoints:
      - name: servicecontrol
        servicecontrol:
          identity: gcp
          serviceName: {{ .Values.ubbagent.serviceName | quote }}
          consumerId: ${MARKETPLACE_CONSUMER_ID}
{{- end }}
