FROM golang:1.25-alpine3.22 AS build

ARG UBBAGENT_REF=14cc2505468cbe15ac0963fa69b6f95e084356b7

RUN apk update \
    && apk upgrade --available \
    && apk add --no-cache make git "openssl>=3.5.6-r0" \
    && openssl version
RUN git clone https://github.com/GoogleCloudPlatform/ubbagent.git /ubbagent-src && \
    cd /ubbagent-src && \
    git checkout "${UBBAGENT_REF}" && \
    rm -rf /ubbagent-src/.git
WORKDIR /ubbagent-src/
RUN go get \
      golang.org/x/crypto@v0.45.0 \
      golang.org/x/net@v0.47.0 \
      golang.org/x/oauth2@v0.34.0 \
      google.golang.org/grpc@v1.79.3 \
      google.golang.org/protobuf@v1.36.10 \
      github.com/golang/glog@v1.2.5 \
      gopkg.in/yaml.v2@v2.2.8 && \
    go mod tidy && \
    mkdir -p /ubbagent-src/bin && \
    go build -o /ubbagent-src/bin/ubbagent github.com/GoogleCloudPlatform/ubbagent

FROM alpine:3.22

ARG MP_SERVICE_NAME=services/molecular-audit-core.endpoints.glassbox-bio-public.cloud.goog
LABEL com.googleapis.cloudmarketplace.product.service.name=${MP_SERVICE_NAME}

RUN apk update && \
    apk upgrade --available && \
    apk add --no-cache "openssl>=3.5.6-r0" libintl ca-certificates && \
    apk add --virtual build_deps gettext && \
    cp /usr/bin/envsubst /usr/local/bin/envsubst && \
    apk del build_deps && \
    openssl version && \
    rm -rf /var/cache/apk/*

COPY --from=build /ubbagent-src/bin/ubbagent /usr/local/bin/ubbagent
COPY deploy/ubbagent-start /usr/local/bin/ubbagent-start
RUN chmod +x /usr/local/bin/ubbagent /usr/local/bin/ubbagent-start

CMD ["/usr/local/bin/ubbagent-start"]
